export const categories = [
    { id: "cat-assistive", name: "Assistive", desc: "Specialized systems equipped with screen readers, magnifiers, and alternative input tools for users with disabilities." },
    { id: "cat-beginners", name: "Beginners", desc: "User-friendly distributions designed for easy installation and a smooth transition from Windows or macOS." },
    { id: "cat-clusters", name: "Clusters", desc: "Designed to link multiple computers together to act as a single, powerful system for complex calculations." },
    { id: "cat-container", name: "Container", desc: "Minimalist systems optimized specifically for running virtual containers like Docker or Podman." },
    { id: "cat-data-rescue", name: "Data Rescue", desc: "Bootable tools used to recover lost files, repair partitions, or fix unbootable operating systems." },
    { id: "cat-declarative", name: "Declarative", desc: "Systems where the entire configuration is defined in a single file, allowing for perfect replication across different hardware." },
    { id: "cat-desktop", name: "Desktop", desc: "General-purpose systems designed for daily tasks like web browsing, document editing, and media consumption." },
    { id: "cat-disk-management", name: "Disk Management", desc: "Specialized environments for partitioning, cloning, and wiping hard drives safely." },
    { id: "cat-education", name: "Education", desc: "Packed with learning software, interactive tools, and curriculum-based apps for students and teachers." },
    { id: "cat-firewall", name: "Firewall", desc: "Hardened systems built to act as a security gateway, protecting local networks from external threats." },
    { id: "cat-forensics", name: "Forensics", desc: "Used by investigators to analyze digital evidence without modifying the data on the target drive." },
    { id: "cat-free-software", name: "Free Software", desc: "Strictly follows the Free Software Foundation's guidelines, containing zero proprietary drivers or binary blobs." },
    { id: "cat-from-ram", name: "From RAM", desc: "Lightweight systems that load entirely into the computer's memory (RAM), resulting in incredible speed and privacy." },
    { id: "cat-gaming", name: "Gaming", desc: "Optimized for high-performance play, often pre-loaded with Steam, Wine, and the latest graphics drivers." },
    { id: "cat-hpc", name: "High Performance Computing", desc: "Designed for supercomputers and scientific research requiring massive parallel processing power." },
    { id: "cat-immutable", name: "Immutable", desc: "A modern approach where the core OS is read-only, preventing accidental breakage and ensuring extreme stability." },
    { id: "cat-kubernetes", name: "Kubernetes", desc: "Tailored specifically for orchestrating large-scale container deployments in cloud environments." },
    { id: "cat-live-medium", name: "Live Medium", desc: "Distros designed to run perfectly from a USB stick or DVD without needing to be installed on a hard drive." },
    { id: "cat-mobile", name: "Mobile", desc: "Built with touch-friendly interfaces for smartphones, tablets, and handheld devices." },
    { id: "cat-multimedia", name: "Multimedia", desc: "A creative's powerhouse pre-configured for professional audio production, video editing, and graphic design." },
    { id: "cat-mythtv", name: "MythTV", desc: "Specifically designed to turn a computer into a digital video recorder (DVR) and home theater hub." },
    { id: "cat-nas", name: "NAS", desc: "Network Attached Storage systems used to manage large amounts of data and share files across a home or office network." },
    { id: "cat-netbooks", name: "Netbooks", desc: "Ultra-lightweight systems optimized for small screens and lower-powered processors found in older portable laptops." },
    { id: "cat-old-computers", name: "Old Computers", desc: "Extremely efficient distros that breathe new life into hardware with very low RAM and aging CPUs." },
    { id: "cat-privacy", name: "Privacy", desc: "Focuses on anonymity by routing traffic through Tor and leaving no digital footprint on the host computer." },
    { id: "cat-raspberry-pi", name: "Raspberry Pi", desc: "Architected specifically for the ARM processors found in Raspberry Pi and other single-board computers." },
    { id: "cat-scientific", name: "Scientific", desc: "Includes specialized libraries and tools for physics, chemistry, biology, and high-level mathematics." },
    { id: "cat-server", name: "Server", desc: "Robust, stable systems without a graphical interface, designed to run web, email, or database services 24/7." },
    { id: "cat-security", name: "Security", desc: "Hardened environments used for penetration testing, vulnerability scanning, and network auditing." },
    { id: "cat-source-based", name: "Source-based", desc: "Advanced distros where the user compiles every piece of software from code to achieve maximum optimization." },
    { id: "cat-specialist", name: "Specialist", desc: "Niche distributions built for a singular, very specific purpose like arcade emulation or radio broadcasting." },
    { id: "cat-telephony", name: "Telephony", desc: "Designed to manage Voice over IP (VoIP) systems, digital switchboards, and communication servers." },
    { id: "cat-thin-client", name: "Thin Client", desc: "Minimal systems that act as a terminal to connect to a more powerful central server that does the actual processing." },
    { id: "cat-legacy", name: "Legacy", desc: "Systems designed to maintain compatibility with very old hardware, software standards, or 32-bit architectures that modern distros have abandoned." },
    { id: "cat-professional", name: "Professional", desc: "Enterprise-grade distributions backed by commercial support, certified for mission-critical workstations and corporate environments." },
];

export const desktops = [
    { id: "de-afterstep", name: "AfterStep", desc: "A window manager originally based on the look of the NeXTSTEP interface, offering a classic and clean aesthetic." },
    { id: "de-android", name: "Android", desc: "The famous mobile interface adapted for use on specific desktop distributions and tablets." },
    { id: "de-awesome", name: "Awesome", desc: "A highly configurable, next-generation tiling window manager for power users who prefer keyboard navigation." },
    { id: "de-budgie", name: "Budgie", desc: "A modern desktop that feels like a mix between ChromeOS and GNOME; it is elegant, simple, and uses the Raven sidebar for notifications." },
    { id: "de-cinnamon", name: "Cinnamon", desc: "The flagship of Linux Mint. It provides a traditional 'Start Menu' layout that is perfect for Windows switchers." },
    { id: "de-cosmic", name: "COSMIC", desc: "A new, high-performance desktop environment built in Rust, focusing on modern aesthetics and advanced tiling features." },
    { id: "de-deepin", name: "Deepin (DDE)", desc: "Widely considered one of the most beautiful desktops, featuring a sleek, translucent dock and highly polished visual effects." },
    { id: "de-enlightenment", name: "Enlightenment", desc: "A lean and fast desktop environment that uses its own unique libraries to provide a futuristic look even on older hardware." },
    { id: "de-gnome", name: "GNOME", desc: "One of the most popular Linux desktops worldwide. It features a minimalist, gesture-focused interface designed to keep you productive." },
    { id: "de-hyprland", name: "Hyprland", desc: "A modern Wayland compositor that features smooth animations, beautiful tiling, and highly customizable 'eye-candy' effects." },
    { id: "de-i3", name: "i3", desc: "The industry standard for tiling window managers. It is lightweight, text-based, and designed entirely around keyboard shortcuts." },
    { id: "de-kde-plasma", name: "KDE Plasma", desc: "The ultimate choice for customization. It looks like Windows by default but can be transformed into almost any interface imaginable." },
    { id: "de-lxqt", name: "LXQt", desc: "A lightweight desktop environment that uses the Qt toolkit. It's fast, low on RAM usage, and great for older laptops." },
    { id: "de-mate", name: "MATE", desc: "A continuation of the classic GNOME 2 interface. It is stable, traditional, and very light on system resources." },
    { id: "de-openbox", name: "Openbox", desc: "A highly minimal window manager. It starts as a blank screen; you right-click to access menus, making it a favorite for minimalist setups." },
    { id: "de-pantheon", name: "Pantheon", desc: "The desktop of elementary OS. It is designed to be simple, consistent, and bears a strong resemblance to macOS." },
    { id: "de-pixel", name: "PIXEL", desc: "The default desktop for Raspberry Pi OS. It is a modified version of LXDE optimized for single-board computers." },
    { id: "de-sway", name: "Sway", desc: "A tiling Wayland compositor that is compatible with i3 configurations, but built for modern graphics technology." },
    { id: "de-unity", name: "Unity", desc: "Originally created by Ubuntu, it features a unique vertical launcher on the left side of the screen and a powerful 'Dash' search." },
    { id: "de-xfce", name: "Xfce", desc: "A classic, lightweight desktop that is incredibly stable. It’s perfect for users who want a fast, traditional experience without the 'bells and whistles'." },
    { id: "de-tiling-wm", name: "Tiling Window Managers", desc: "Includes dwm, bspwm, qtile, and xmonad. These systems don't overlap windows; instead, they tile them in a grid for maximum efficiency." },
    { id: "de-mobile-ui", name: "Mobile Interfaces", desc: "Includes Phosh, Lomiri, and Plasma Mobile. These are designed specifically for touchscreens and mobile phone hardware." },
    { id: "de-niche-wm", name: "Classic & Niche WMs", desc: "Includes Blackbox, Fluxbox, FVWM, and IceWM. These are ultra-lightweight managers from the early days of Linux, still loved for their speed." },
    { id: "de-no-desktop", name: "No Desktop", desc: "A 'Headless' or Terminal-only environment. Common for servers where every bit of RAM is saved by not running a graphical interface." },
    { id: "de-windows-shell", name: "Windows Shell", desc: "The standard graphical interface for Windows 10/11. It includes the taskbar, Start menu, and File Explorer." },
    { id: "de-fluent-design", name: "Fluent Design", desc: "Microsoft's modern design language used in Windows 11, featuring translucency (Mica), rounded corners, and depth effects." },
    { id: "de-server-core", name: "Server Core", desc: "A minimal installation option for Windows Server that removes the graphical user interface (GUI) to reduce the system footprint and security risk." },
];
